spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/car-test?serverTimezone=GMT%2B8
  mail:
    #邮件协议smtp
    host: smtp.qq.com
    #发送者的邮件的用户名
    username: 657050518@qq.com
    #使用的编码
    default-encoding: utf-8
    #移动端客户授权码(在邮箱中设置)
    password: hmwoboiiskbobdbe
server:
  port: 8090