spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/car-test?serverTimezone=GMT%2B8
#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .html


server:
  port: 8090